name: Validate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-validate
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: true
      matrix:
        node-version: [24.x]
        os: [ubuntu-24.04]

    env:
      NUXT_PUBLIC_APP_BASE_URL: "http://localhost:3000"
      NUXT_PUBLIC_APP_BOTS: "disabled"
      NUXT_PUBLIC_APP_IMPRINT_CUSTOM_CONFIG: "disabled"
      NUXT_PUBLIC_APP_IMPRINT_SERVICE_BASE_URL: "${{ vars.NUXT_PUBLIC_APP_IMPRINT_SERVICE_BASE_URL }}"
      NUXT_PUBLIC_APP_MATOMO_BASE_URL: "${{ vars.NUXT_PUBLIC_APP_MATOMO_BASE_URL }}"
      NUXT_PUBLIC_APP_MATOMO_ID: "${{ vars.NUXT_PUBLIC_APP_MATOMO_ID }}"
      NUXT_PUBLIC_APP_SERVICE_ID: "${{ vars.SERVICE_ID }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint:check

      - name: Typecheck
        run: pnpm run types:check

      - name: Test
        run: pnpm run test

      - name: Get playwright version
        run: |
          PLAYWRIGHT_VERSION=$(pnpm ls @playwright/test --json | jq --raw-output '.[0].devDependencies["@playwright/test"].version')
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache playwright browsers
        uses: actions/cache@v5
        id: cache-playwright-browsers
        with:
          path: "~/.cache/ms-playwright"
          key: ${{ matrix.os }}-playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install playwright browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps
      - name: Install playwright browsers (os dependencies)
        if: steps.cache-playwright-browsers.outputs.cache-hit == 'true'
        run: pnpm exec playwright install-deps

      - name: Cache nuxt build output
        uses: actions/cache@v5
        with:
          path: |
            .nuxt
            dist
          key: ${{ matrix.os }}-nuxt-${{ hashFiles('dist') }}
          restore-keys: |
            ${{ matrix.os }}-nuxt-

      - name: Build app
        run: pnpm run build

      - name: Run e2e tests
        run: pnpm run test:e2e

      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  build-deploy:
    if: ${{ github.event_name == 'push' }}
    needs: [validate]
    uses: ./.github/workflows/build-deploy.yaml
    secrets: inherit
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#access-and-permissions
    permissions:
      contents: read
      packages: write
